Lab04_LMK/Models/ShoppingCart.cs
namespace Lab04_LMK.Models
{
	public class ShoppingCart
	{
		public List<CartItem> Items { get; set; } = new List<CartItem>();
		public void AddItem(CartItem item)
		{
			var existingItem = Items.FirstOrDefault(i => i.ProductId ==
			item.ProductId);
			if (existingItem != null)
			{
				existingItem.Quantity += item.Quantity;
			}
			else
			{
				Items.Add(item);
			}
		}
		public void RemoveItem(int productId)
		{
			Items.RemoveAll(i => i.ProductId == productId);
		}
		// Các phương thức khác...
	}
}

Lab04_LMK/Controllers/ShoppingCartController.cs
using Lab04_LMK.Data;
using Lab04_LMK.Extensions;
using Lab04_LMK.Models;
using Lab04_LMK.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Lab04_LMK.Controllers
{
    [Authorize]
    public class ShoppingCartController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        public ShoppingCartController(ApplicationDbContext context,
        UserManager<ApplicationUser> userManager, IProductRepository
        productRepository)
        {
            _productRepository = productRepository;
            _context = context;
            _userManager = userManager;
        }

        public IActionResult Checkout()
        {
            return View(new Order());
        }
        [HttpPost]
        public async Task<IActionResult> Checkout(Order order)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart == null || !cart.Items.Any())
            {
                // Xử lý giỏ hàng trống...
                return RedirectToAction("Index");
            }
            var user = await _userManager.GetUserAsync(User);
            order.UserId = user.Id;
            order.OrderDate = DateTime.UtcNow;
            order.TotalPrice = cart.Items.Sum(i => i.Price * i.Quantity);
            order.OrderDetails = cart.Items.Select(i => new OrderDetail
            {
                ProductId = i.ProductId,
                Quantity = i.Quantity,
                Price = i.Price
            }).ToList();
            _context.Orders.Add(order);
            await _context.SaveChangesAsync();
            HttpContext.Session.Remove("Cart");
            return View("OrderCompleted", order); // Trang xác nhận hoàn thành đơn hàng
        }


        public async Task<IActionResult> AddToCart(int productId, int quantity)
        {
            // Giả sử bạn có phương thức lấy thông tin sản phẩm từ productId
            var product = await GetProductFromDatabase(productId);
            var cartItem = new CartItem
            {
                ProductId = productId,
                Name = product.Name,
                Price = product.Price,
                Quantity = quantity
            };
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new
            ShoppingCart();
            cart.AddItem(cartItem);
            HttpContext.Session.SetObjectAsJson("Cart", cart);
            return RedirectToAction("Index");
        }
        public IActionResult Index()
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart") ?? new
            ShoppingCart();
            return View(cart);
        }
        // Các actions khác...
        private async Task<Product> GetProductFromDatabase(int productId)
        {
            // Truy vấn cơ sở dữ liệu để lấy thông tin sản phẩm
            var product = await _productRepository.GetByIdAsync(productId);
            return product;
        }
        public IActionResult RemoveFromCart(int productId)
        {
            var cart = HttpContext.Session.GetObjectFromJson<ShoppingCart>("Cart");
            if (cart is not null)
            {
                cart.RemoveItem(productId);
                // Lưu lại giỏ hàng vào Session sau khi đã xóa mục
                HttpContext.Session.SetObjectAsJson("Cart", cart);
            }
            return RedirectToAction("Index");
        }
    }
}

Lab04_LMK/Views/ShoppingCart/CheckOut.cshtml
@model Order
<style>
    /* Style for the form container */
    .form-container {
        max-width: 500px;
        margin: 0 auto;
        padding: 20px;
        background-color: #f9f9f9;
        border-radius: 5px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    /* Style for form labels */
    .form-group label {
        font-weight: bold;
    }

    /* Style for form input fields */
    .form-control {
        width: 100%;
        padding: 10px;
        margin-top: 5px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 3px;
        box-sizing: border-box;
    }

        /* Style for form textarea */
        .form-control textarea {
            height: 100px;
            resize: vertical; /* Allow vertical resizing */
        }

    /* Style for submit button */
    .btn-primary {
        display: inline-block;
        padding: 10px 20px;
        background-color: #007bff;
        color: #fff;
        border: none;
        border-radius: 3px;
        cursor: pointer;
    }

        /* Style for submit button hover */
        .btn-primary:hover {
            background-color: #0056b3;
        }

</style>
<div class="form-container">
    <h2>Checkout</h2>
    <form asp-action="Checkout" method="post">
        <div class="form-group">
            <label asp-for="ShippingAddress">Shipping Address</label>
            <input asp-for="ShippingAddress" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Notes">Notes</label>
            <textarea asp-for="Notes" class="form-control"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Place Order</button>
    </form>
</div>

Lab04_LMK/Views/ShoppingCart/Index.cshtml
@model ShoppingCart
<h2>Your Cart</h2>
<style>
	/* Style for the table */
	table {
		width: 100%;
		border-collapse: collapse;
		margin-bottom: 20px;
	}

	/* Style for table headers */
	th {
		background-color: #f2f2f2;
		border: 1px solid #dddddd;
		padding: 8px;
		text-align: left;
	}

	/* Style for table cells */
	td {
		border: 1px solid #dddddd;
		padding: 8px;
	}

	/* Style for the remove link */
	a {
		color: #ff4500;
		text-decoration: none;
	}

		/* Style for the checkout link */
		a.checkout {
			display: block;
			width: 100px;
			padding: 10px;
			text-align: center;
			background-color: #4caf50;
			color: white;
			text-decoration: none;
			border-radius: 5px;
		}

			/* Style for the checkout link hover effect */
			a.checkout:hover {
				background-color: #45a049;
			}

</style>
<table>
	<tr>
		<th>Product</th>
		<th>Quantity</th>
		<th>Price</th>
		<th>Total</th>
		<th>Action</th>
	</tr>
	@foreach (var item in Model.Items)
	{
		<tr>
			<td>@item.Name</td>
			<td>@item.Quantity</td>
			<td>@item.Price</td>
			<td>@(item.Price * item.Quantity)</td>
			<td>
				<a asp-action="RemoveFromCart" asp-route-productId="@item.ProductId">Remove</a>
			</td>
		</tr>
	}

	<tr>
		<td colspan="4"></td> <!-- Tạo một cell trống để căn chỉnh -->
		<td>
			<a asp-action="Checkout" asp-controller="ShoppingCart">Thanh Toán</a>
		</td>
	</tr>
</table>

Lab04_LMK/Views/ShoppingCart/OrderCompleted.cshtml
@model Order

<style>
    /* Style for the heading */
    h2 {
        font-size: 24px;
        color: #333;
    }

    /* Style for the section headers */
    h3 {
        font-size: 20px;
        color: #555;
        margin-top: 20px;
    }

    /* Style for the paragraph */
    p {
        font-size: 16px;
        color: blue;
    }

    /* Style for the table */
    table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
    }

    /* Style for table headers */
    th {
        background-color: #f2f2f2;
        border: 1px solid #ddd;
        padding: 8px;
        text-align: left;
    }

    /* Style for table cells */
    td {
        border: 1px solid #ddd;
        padding: 8px;
    }

    /* Style for alternating rows */
    tr:nth-child(even) {
        background-color: #f9f9f9;
    }

    /* Style for total price section */
    .total-price {
        margin-top: 20px;
        font-size: 18px;
        color: #333;
        font-weight: bold;
    }

</style>
<h2>Order Completed</h2>

<h3>Order Details</h3>
<p>Order ID: @Model.Id</p>
<p>Order Date: @Model.OrderDate</p>
<p>Shipping Address: @Model.ShippingAddress</p>
<p>Note: @Model.Notes</p>
<!-- Display other order details as needed -->

<h3>Ordered Items</h3>
<table>
    <tr>
        <th>Product</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Total</th>
    </tr>
    @foreach (var item in Model.OrderDetails)
    {
        <tr>
            <td>@item.ProductId</td>
            <td>@item.Quantity</td>
            <td>@item.Price</td>
            <td>@(item.Price * item.Quantity)</td>
        </tr>
    }
</table>

<h3>Total Price: @Model.TotalPrice</h3>